public final class kotlinx.coroutines.CancelledContinuation extends kotlinx.coroutines.CompletedExceptionally
{
    private static final java.util.concurrent.atomic.AtomicIntegerFieldUpdater _resumed$FU;
    private volatile int _resumed;

    static void <clinit>()
    {
        java.util.concurrent.atomic.AtomicIntegerFieldUpdater $r0;

        $r0 = staticinvoke <java.util.concurrent.atomic.AtomicIntegerFieldUpdater: java.util.concurrent.atomic.AtomicIntegerFieldUpdater newUpdater(java.lang.Class,java.lang.String)>(class "Lkotlinx/coroutines/CancelledContinuation;", "_resumed");

        <kotlinx.coroutines.CancelledContinuation: java.util.concurrent.atomic.AtomicIntegerFieldUpdater _resumed$FU> = $r0;

        return;
    }

    public void <init>(kotlin.coroutines.Continuation, java.lang.Throwable, boolean)
    {
        java.lang.Throwable $r2;
        kotlin.coroutines.Continuation $r1;
        java.util.concurrent.CancellationException $r3;
        java.lang.StringBuilder $r4;
        kotlinx.coroutines.CancelledContinuation r0;
        java.lang.String $r5;
        boolean $z0;

        r0 := @this: kotlinx.coroutines.CancelledContinuation;

        $r1 := @parameter0: kotlin.coroutines.Continuation;

        $r2 := @parameter1: java.lang.Throwable;

        $z0 := @parameter2: boolean;

        if $r2 != null goto label1;

        $r3 = new java.util.concurrent.CancellationException;

        $r4 = new java.lang.StringBuilder;

        specialinvoke $r4.<java.lang.StringBuilder: void <init>()>();

        $r4 = virtualinvoke $r4.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Continuation ");

        $r4 = virtualinvoke $r4.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r1);

        $r4 = virtualinvoke $r4.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" was cancelled normally");

        $r5 = virtualinvoke $r4.<java.lang.StringBuilder: java.lang.String toString()>();

        specialinvoke $r3.<java.util.concurrent.CancellationException: void <init>(java.lang.String)>($r5);

        $r2 = (java.lang.Throwable) $r3;

        goto label1;

     label1:
        specialinvoke r0.<kotlinx.coroutines.CompletedExceptionally: void <init>(java.lang.Throwable,boolean)>($r2, $z0);

        r0.<kotlinx.coroutines.CancelledContinuation: int _resumed> = 0;

        return;
    }

    public final boolean makeResumed()
    {
        java.util.concurrent.atomic.AtomicIntegerFieldUpdater $r1;
        kotlinx.coroutines.CancelledContinuation r0;
        boolean $z0;

        r0 := @this: kotlinx.coroutines.CancelledContinuation;

        $r1 = <kotlinx.coroutines.CancelledContinuation: java.util.concurrent.atomic.AtomicIntegerFieldUpdater _resumed$FU>;

        $z0 = virtualinvoke $r1.<java.util.concurrent.atomic.AtomicIntegerFieldUpdater: boolean compareAndSet(java.lang.Object,int,int)>(r0, 0, 1);

        return $z0;
    }
}
