final class kotlinx.coroutines.future.ContinuationHandler extends java.lang.Object implements java.util.function.BiFunction
{
    public volatile kotlin.coroutines.Continuation cont;

    public void <init>(kotlin.coroutines.Continuation)
    {
        kotlin.coroutines.Continuation $r1;
        kotlinx.coroutines.future.ContinuationHandler r0;

        r0 := @this: kotlinx.coroutines.future.ContinuationHandler;

        $r1 := @parameter0: kotlin.coroutines.Continuation;

        specialinvoke r0.<java.lang.Object: void <init>()>();

        r0.<kotlinx.coroutines.future.ContinuationHandler: kotlin.coroutines.Continuation cont> = $r1;

        return;
    }

    public volatile java.lang.Object apply(java.lang.Object, java.lang.Object)
    {
        java.lang.Throwable $r3;
        kotlin.Unit r4;
        kotlinx.coroutines.future.ContinuationHandler r0;
        java.lang.Object $r1, $r2;

        r0 := @this: kotlinx.coroutines.future.ContinuationHandler;

        $r1 := @parameter0: java.lang.Object;

        $r2 := @parameter1: java.lang.Object;

        $r3 = (java.lang.Throwable) $r2;

        virtualinvoke r0.<kotlinx.coroutines.future.ContinuationHandler: void apply(java.lang.Object,java.lang.Throwable)>($r1, $r3);

        r4 = <kotlin.Unit: kotlin.Unit INSTANCE>;

        return r4;
    }

    public void apply(java.lang.Object, java.lang.Throwable)
    {
        java.lang.Throwable $r2, $r6, $r7;
        kotlin.coroutines.Continuation r3;
        kotlinx.coroutines.future.ContinuationHandler r0;
        kotlin.Result$Companion $r4;
        java.util.concurrent.CompletionException $r5;
        java.lang.Object $r1;
        boolean $z0;

        r0 := @this: kotlinx.coroutines.future.ContinuationHandler;

        $r1 := @parameter0: java.lang.Object;

        $r2 := @parameter1: java.lang.Throwable;

        r3 = r0.<kotlinx.coroutines.future.ContinuationHandler: kotlin.coroutines.Continuation cont>;

        if r3 != null goto label1;

        return;

     label1:
        if $r2 != null goto label2;

        $r4 = <kotlin.Result: kotlin.Result$Companion Companion>;

        $r1 = staticinvoke <kotlin.Result: java.lang.Object constructor-impl(java.lang.Object)>($r1);

        interfaceinvoke r3.<kotlin.coroutines.Continuation: void resumeWith(java.lang.Object)>($r1);

        return;

     label2:
        $z0 = $r2 instanceof java.util.concurrent.CompletionException;

        if $z0 == 0 goto label3;

        $r5 = (java.util.concurrent.CompletionException) $r2;

        goto label4;

     label3:
        $r5 = null;

     label4:
        if $r5 == null goto label5;

        $r6 = virtualinvoke $r5.<java.util.concurrent.CompletionException: java.lang.Throwable getCause()>();

        $r7 = $r6;

        if $r6 != null goto label6;

     label5:
        $r7 = $r2;

     label6:
        $r4 = <kotlin.Result: kotlin.Result$Companion Companion>;

        $r1 = staticinvoke <kotlin.ResultKt: java.lang.Object createFailure(java.lang.Throwable)>($r7);

        $r1 = staticinvoke <kotlin.Result: java.lang.Object constructor-impl(java.lang.Object)>($r1);

        interfaceinvoke r3.<kotlin.coroutines.Continuation: void resumeWith(java.lang.Object)>($r1);

        return;
    }
}
